/**
 * Claude adapter: builds CLAUDE.md from the project context. CLAUDE.md is a
 * generated artifact (supported by the plan's file-ownership table) and is
 * synced from .project-bootstrap/AGENTS.md.
 */
import type { ProjectContext } from '../domain/project-context.js';
import type { AiAdapter } from './ai-adapter.js';

export class ClaudeAdapter implements AiAdapter {
  readonly id = 'claude' as const;
  readonly name = 'Claude';

  buildContext(project: ProjectContext): string {
    const lines: string[] = [
      '# CLAUDE.md',
      '',
      '> Generated by project-bootstrap. Edit the source of truth at `.project-bootstrap/` and `AGENTS.md`; run `project-bootstrap sync` to regenerate.',
      '',
      '## Project',
      '',
      `- Language: ${project.tooling.language}`,
      `- Framework: ${project.tooling.framework}`,
      `- Package manager: ${project.tooling.packageManager}`,
      `- Runtime: ${project.tooling.runtime}`,
    ];
    if (project.tooling.commands.length > 0) {
      lines.push('', '## Commands');
      for (const command of project.tooling.commands) {
        lines.push(`- \`${command}\``);
      }
    }
    lines.push('', '## Rules', '', 'Follow the engineering rules in `.project-bootstrap/rules/`.');
    lines.push(
      '',
      '## Workflow',
      '',
      'Follow the development workflow in `.project-bootstrap/workflows/`.',
    );
    return lines.join('\n');
  }
}
